myMovieReviews/movies/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('', movies_list),
    path("create/",movies_create),
    path("<int:pk>/",movies_read),
    path("<int:pk>/update/", movies_update),
    path("<int:pk>/delete/",movies_delete),
]

myMovieReviews/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
  CHOICES = (
        ('스릴러 영화', '스릴러 영화'),
        ('코미디 영화','코미디 영화'),
        ('액션 영화', '액션 영화'),
        ('sf 영화','sf 영화'),
        ('로맨스 영화','로맨스 영화'),
        ('공포 영화','공포 영화'),
        ('전쟁 영화', '전쟁 영화'),
        ('테스트','테스트'),
    )
  title = models.CharField(max_length=32)
  release_time = models.CharField(max_length=32)
  director = models.CharField(max_length=32)
  actor = models.CharField(max_length=32)
  genre = models.CharField(max_length=32, choices=CHOICES)
  star = models.CharField(max_length=32)
  time = models.CharField(max_length=32)
  content =  models.TextField()

myMovieReviews/movies/views.py
from django.shortcuts import render, HttpResponse , redirect, get_object_or_404
from .models import *
# Create your views here.

def movies_list(request):
  movies = Movie.objects.all().order_by(('title'))
  context = {
    "movies" : movies
  }
  return render(request,'movies_list.html',context)

def movies_create(request):
  if request.method == "POST":
    Movie.objects.create(
    title = request.POST["title"],
    release_time = request.POST["release_time"],
    director = request.POST["director"],
    actor = request.POST["actor"],
    genre = request.POST["genre"],
    star = request.POST["star"],
    time = request.POST["time"],
    content =  request.POST["content"],
    )
    return redirect("/movies")
  return render(request,"movies_create.html")

def movies_read(request, pk):
  movie = get_object_or_404(Movie, pk=pk)
  movie_time_hour = int(movie.time) // 60
  movie_time_min = int(movie.time) - (movie_time_hour*60)
  context = {
    "movie" : movie,
    "movie_time_hour" : movie_time_hour,
    "movie_time_min" : movie_time_min,
  }
  return render(request, "movies_read.html", context)

def movies_update(request, pk):
  movie = get_object_or_404(Movie, pk=pk)
  if request.method == 'POST':
    movie.title = request.POST["title"]
    movie.release_time = request.POST['release_time']
    movie.director = request.POST['director']
    movie.actor = request.POST['actor']
    movie.genre = request.POST['genre']
    movie.star = request.POST['star']
    movie.time = request.POST['time']
    movie.content = request.POST['content']
    movie.save()
    return redirect(f"/movies/{movie.id}")
  
  context = {
    'movie' : movie
  }
  return render(request,'movies_update.html', context)

def movies_delete(request,pk):
  if request.method == 'POST':
    movie = Movie.objects.get(id = pk)
    movie.delete()
  return redirect('/movies')

myMovieReviews/movies/templates/movies_create.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>my Movie Reviews</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/read.css' %}" />
  </head>
  <body>
    <h1>리뷰 작성하기</h1>

    <form action="/movies/create/" method="post" class="movie_list">
      {% csrf_token %}
      <span>제목 : </span><input name="title" placeholder="제목" />
      <span>개봉년도 : </span
      ><input name="release_time" placeholder="개봉년도" />

      <span>감독 : </span><input name="director" placeholder="감독" />
      <span>주연 : </span><input name="actor" placeholder="주연" />
      <span>장르 :</span>
      <select name="genre" required="" id="id_genre">
        <option value="" selected="">---------</option>
        <option value="스릴러 영화">스릴러 영화</option>
        <option value="로맨스 영화">로맨스 영화</option>
        <option value="액션 영화">액션 영화</option>
        <option value="sf 영화">sf 영화</option>
        <option value="코미디 영화">코미디 영화</option>
        <option value="공포 영화">공포 영화</option>
        <option value="전쟁 영화">전쟁 영화</option>
      </select>
      <div>별점 :</div>
      <input name="star" placeholder="별점" value="{{movie.star}}" />
      <div>러닝타임 :</div>
      <input name="time" placeholder="러닝타임" value="{{movie.time}}" />
      <div>리뷰 :</div>
      <textarea name="content" cols="30" rows="10" placeholder="리뷰">
  {{movie.content}}</textarea
      >
      <div>
        <input type="submit" value="작성완료" class="btn" />
      </div>
    </form>
  </body>
</html>

myMovieReviews/movies/templates/movies_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>my Movie Reviews</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/list.css' %}" />
  </head>
  <body>
    <h3>영화 리뷰 게시판</h3>
    <div class="create"><a href="/movies/create/">리뷰 작성</a></div>
    <div class="movie_lists">
      {% for movie in movies %}
      <div class="movie_list">
        <p><a href="/movies/{{movie.id}}/">{{movie.id}}. {{movie.title}}</a></p>
        <p>개봉 년도 : {{movie.release_time}}</p>
        <p>장르 : {{movie.genre}}</p>
        <p>별점 : {{movie.star}}</p>
      </div>
      {% endfor %}
    </div>
  </body>
</html>

myMovieReviews/movies/templates/movies_read.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>my Movie Reviews</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/read.css' %}" />
  </head>
  <body>
    <div class="movie_list">
      <h1>{{ movie.title }}</h1>
      <p>작가 : {{ movie.director }}</p>
      <br />
      <p>주연 : {{ movie.actor }}</p>
      <br />
      <p>장르 : {{ movie.genre }}</p>
      <br />
      <p>별점 : {{ movie.star }}</p>
      <br />
      <p>러닝타임 : {{ movie_time_hour}}시간 {{movie_time_min}}분</p>
      <br />
      <p>내용 : {{ movie.content }}</p>
      <br />
      <!-- #리뷰리스트화면으로 돌아가기 -->
      <a href="/movies/">my Movie reviews</a>
      <!-- 수정하기 버튼 -->
      <a href="/movies/{{movie.id}}/update/">수정하기</a>
      <!-- 리뷰 삭제하기 -->
      <form action="/movies/{{movie.id}}/delete/" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제하기" class="btn" />
      </form>
    </div>
  </body>
</html>

myMovieReviews/movies/templates/movies_update.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>my Movie Reviews</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/read.css' %}" />
  </head>
  <body>
    <h1>리뷰 수정하기</h1>
    <form
      action="/movies/{{movie.id}}/update/"
      method="post"
      class="movie_list"
    >
      {% csrf_token %}
      <span>제목 : </span
      ><input name="title" placeholder="제목" value="{{movie.title}}" />
      <span>개봉년도 : </span
      ><input
        name="release_time"
        placeholder="개봉년도"
        value="{{movie.release_time}}"
      />

      <span>감독 : </span
      ><input name="director" placeholder="감독" value="{{movie.director}}" />

      <span>주연 : </span
      ><input name="actor" placeholder="주연" value="{{movie.actor}}" />
      <span>장르 :</span>
      <select name="genre" required="" id="id_genre">
        <option value="" selected="">---------</option>
        <option value="스릴러 영화">스릴러 영화</option>
        <option value="로맨스 영화">로맨스 영화</option>
        <option value="액션 영화">액션 영화</option>
        <option value="sf 영화">sf 영화</option>
        <option value="코미디 영화">코미디 영화</option>
        <option value="공포 영화">공포 영화</option>
        <option value="전쟁 영화">전쟁 영화</option>
      </select>
      <div>별점 :</div>
      <input name="star" placeholder="별점" value="{{movie.star}}" />
      <div>러닝타임 :</div>
      <input name="time" placeholder="러닝타임" value="{{movie.time}}" />
      <div>리뷰 :</div>
      <textarea name="content" cols="30" rows="10" placeholder="리뷰">
  {{movie.content}}</textarea
      >
      <div>
        <input type="submit" value="작성완료" class="btn" />
      </div>
    </form>
  </body>
</html>