piro20_Ajax_Pirostagram/server/apps/comments/urls.py
from django.urls import path
from .views import *

app_name = 'comments'

urlpatterns = [
    path('create/',create,name='create'),
    path('delete/<int:pk>', delete, name='delete'),
]

piro20_Ajax_Pirostagram/server/apps/posts/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('',main,name = 'main'),
    path('create/',create,name='create'),
    path('detail/<int:pk>/',detail,name='detail'),
    path('like_ajax/', like_ajax, name='like_ajax'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

piro20_Ajax_Pirostagram/server/apps/users/urls.py
from django.urls import path
from . import views

# from .views import CustomSignupView
app_name = "users"

urlpatterns = [
    path("logout/", views.logout, name="logout"),
]

piro20_Ajax_Pirostagram/server/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.posts.urls')),
    path('comments/',include('apps.comments.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/',include('apps.users.urls')),
]

piro20_Ajax_Pirostagram/server/apps/comments/models.py
from django.db import models
from apps.users.models import User

# Create your models here.
class Comment(models.Model):
  comment = models.TextField()
  post_id = models.IntegerField()
  user = models.ForeignKey(User, on_delete=models.CASCADE,)

piro20_Ajax_Pirostagram/server/apps/posts/models.py
from django.db import models
from apps.comments.models import *
from apps.users.models import User
# Create your models here.
class Post(models.Model):
  title = models.CharField(max_length=24)
  content = models.TextField()
  like = models.IntegerField(default = 0)
  comments = models.ManyToManyField(Comment, blank=True)
  photo = models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')
  user = models.ForeignKey(User, on_delete=models.CASCADE,)
  likes = models.ManyToManyField(User, related_name='likes', blank=True)
  is_like = models.BooleanField(blank=True)
  def post_comment(self):
    return self.comments.filter(post_id=self.id)
  def user_liked(self, user):
    return self.likes.filter(id=user.id).exists()

piro20_Ajax_Pirostagram/server/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    password = models.CharField(max_length=16)
    

piro20_Ajax_Pirostagram/server/apps/posts/forms.py
from django import forms

from .models import *

class PostForm(forms.ModelForm):
    
    # title = forms.CharField(
    #     label='게시글 제목',
    #     widget=forms.TextInput(
    #         attrs={
    #             'class' : 'signup-input'
    #         }
    #     )
    # )
    # content = forms.Textarea(
    #     label='게시글 내용',
    #     widget=forms.TextInput(
    #         attrs={
    #             'class' : 'signup-input'
    #         }
    #     )
    # )
    
    class Meta:
        model = Post
        fields = ('title','content','photo')

piro20_Ajax_Pirostagram/server/apps/users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignupForm(UserCreationForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    email = forms.EmailField(
      label='이메일',
      widget=forms.EmailInput(
        attrs={
          'class' : 'signup-input'
        }
      )        
    )
    
    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    class Meta:
        model = User
        fields = ['username','password1', 'password2']

piro20_Ajax_Pirostagram/server/apps/comments/views.py
from django.shortcuts import render,redirect

from apps.posts.models import Post
from .models import *
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def create(request):
  req = json.loads(request.body)
  postId = req['id']
  print('1')
  userName = req['username']
  print('2')
  post = Post.objects.get(id=postId)
  user1 = User.objects.get(username = userName)
  print(user1)
  comment = Comment.objects.create(
    user = user1,
    comment = req["comment"],
    post_id = postId,
  )
  comment_id = comment.id
  post.comments.add(comment)
  return JsonResponse({'id':postId,'comment':req["comment"], 'comment_id':comment_id, 'user':comment.user.username})





@csrf_exempt
def delete(request, pk):
  req = json.loads(request.body)
  comment_id = req['comment_id']
  comment = Comment.objects.get(id=comment_id)
  comment.delete()
  return JsonResponse({'id':pk,'comment_id':comment_id})

piro20_Ajax_Pirostagram/server/apps/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
# Create your views here.

def main(request):
  posts = Post.objects.all().order_by('id')
  for post in posts:
    post.is_like = post.user_liked(request.user)
  ctx = {
    'posts' : posts
  }
  return render(request,'posts/main.html',ctx)

def create(request):
  if request.method == 'POST':
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
      post = form.save(commit=False)  
      post.user = request.user  
      post.save() 
      
      return redirect('posts:main')
    else:
      ctx={
        'post':post,
      }
      return render(request, 'post/create.html',ctx)
  else:
    post = PostForm()
    ctx={
        'post': post,
    }
    return render(request, 'posts/create.html', ctx)

def detail(request,pk):
  post = get_object_or_404(Post, pk=pk)
  post.is_like=post.user_liked(request.user)
  comments = post.comments.all()
  ctx = {
    'comments':comments,
    "post" : post,
  }
  return render(request, "posts/detail.html", ctx)


########## ajax
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def like_ajax(request):
    req = json.loads(request.body)
    post_id = req['id']
    post_like = req['like']
    post_username = req['username']
    post = Post.objects.get(id=post_id)
    user = User.objects.get(username=post_username)

    
    if post.user_liked(user):
      post.likes.remove(user)
      post.like -= 1
    else:
      post.likes.add(user)
      post.like += 1
    post.save()
    
    return JsonResponse({'id':post_id,'type':post.user_liked(user),'like':post.like})

piro20_Ajax_Pirostagram/server/apps/users/views.py
from django.shortcuts import render,redirect
from django.contrib import auth
# Create your views here.
def logout(request):
    auth.logout(request)
    return redirect('posts:main')

piro20_Ajax_Pirostagram/server/templates/posts/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form
      method="POST"
      action=""
      class="signup-block"
      enctype="multipart/form-data"
    >
      <h1>게시물 작성</h1>
      {% csrf_token %} {{ post }}
      <input type="submit" value="SignUp" class="btn-neon sbmit-btn" />
    </form>
  </body>
</html>

piro20_Ajax_Pirostagram/server/templates/posts/detail.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.css"
    />
    <link rel="stylesheet" href="{% static 'posts/css/style.css' %}" />
  </head>
  <body>
    <div class="header">
      <a class="menu-btn title" href="{% url 'posts:main' %}">Pirostargram</a>
      {% if user.is_authenticated %}

      <span>{{user.username}} 님이 로그인중</span>
      <a class="menu-btn" href="{% url 'posts:create' %}">게시글 작성하기</a>
      <a href="{% url 'users:logout' %}">로그아웃</a>
      {%endif %}
      <a class="menu-btn title" href="{% url 'posts:main' %}">메뉴</a>
    </div>
    <div class="post">
      {% if post.photo.url != '' %}
      <img src="{{post.photo.url}}" alt="제품 이미지" class="img" /><br />
      {% else %}
      <img
        src="{% static 'posts/image/no_img.png' %}"
        alt="대체 텍스트"
        class="img"
      /><br />
      {% endif %}
      <div class="post_title">제목 : {{post.title}}</div>
      <div class="post_user">작성자 : {{post.user.username}}</div>
      <div class="post_content">내용 : {{post.content}}</div>
      <div class="post-id-{{ post.id }}">
        <div
          class="btn btn-primary post__like"
          onclick="onClickLike({{ post.id }},{{post.like}},'{{user.username}}')"
        >
          {% if post.is_like %}
          <i class="fa-solid fa-heart"></i>
          <div>총 좋아요 : {{post.like}}</div>
          {% else %}
          <i class="fa-regular fa-heart"></i>
          <div>총 좋아요 : {{post.like}}</div>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="comment-list-{{post.id}} comment-list">
      {% for comment1 in comments %}
      <div class="comment comment{{comment1.id}}">
        {{comment1.comment}}
        <div class="comment-user">{{comment1.user.username}}</div>
        {% if comment1.user.username == user.username %}
        <div
          class="btn btn-primary comment-create"
          onclick="onClickDelete({{ post.id }},{{comment1.id}})"
        >
          삭제
        </div>
        {% endif %}
      </div>
      {% endfor %}
    </div>

    <div class="comment-id-{{ post.id }} comment-new">
      <input
        type="text"
        id="commentInput-{{ post.id }}"
        placeholder="댓글 내용을 입력하세요"
      />
      <div
        class="btn btn-primary comment-create"
        onclick="onClickCreate({{ post.id }},document.getElementById('commentInput-{{ post.id }}').value,'{{user.username}}')"
      >
        등록
      </div>
    </div>
    <script>
      const requestClick = new XMLHttpRequest();

      const onClickCreate = (id, comment, username) => {
        console.log(1);
        const url = "/comments/create/";
        requestClick.open("POST", url, true);
        requestClick.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        console.log("1");
        requestClick.send(
          JSON.stringify({ id: id, comment: comment, username: username })
        );
        console.log("2");
        requestClick.onreadystatechange = () => {
          if (requestClick.readyState === XMLHttpRequest.DONE) {
            if (requestClick.status < 400) {
              const { id, comment, comment_id, user } = JSON.parse(
                requestClick.response
              );
              console.log("3");
              const element = document.querySelector(`.comment-list-${id}`);
              element.innerHTML =
                element.innerHTML +
                `<div class='comment comment${comment_id}'>${comment}  <div class="comment-user">${user} </div><div
                  class="btn btn-primary comment-create"
                  onclick="onClickDelete({{ post.id }},${comment_id})"
                >
                  삭제
                </div></div>`;
            }
          }
        };
      };

      //레디스테이트가 변할때마다 이벤트리스너처럼 자동작동

      const onClickDelete = (id, comment_id) => {
        const url = `/comments/delete/${id}`;
        requestClick.open("POST", url, true);
        requestClick.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestClick.send(JSON.stringify({ id: id, comment_id: comment_id }));

        requestClick.onreadystatechange = () => {
          if (requestClick.readyState === XMLHttpRequest.DONE) {
            if (requestClick.status < 400) {
              const { id, comment_id } = JSON.parse(requestClick.response);
              console.log(comment_id);
              const element = document.querySelector(`.comment${comment_id}`);
              console.log("poss");
              element.innerHTML = ``;
            }
          }
        };
      };

      //레디스테이트가 변할때마다 이벤트리스너처럼 자동작동
      const onClickLike = (id, like, username) => {
        const requestLike = new XMLHttpRequest();
        const url = "/like_ajax/";
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestLike.send(
          JSON.stringify({ id: id, like: like, username: username })
        );
        requestLike.onreadystatechange = () => {
          if (requestLike.readyState === XMLHttpRequest.DONE) {
            console.log("2");
            if (requestLike.status < 400) {
              const { id, type, like } = JSON.parse(requestLike.response);
              const element = document.querySelector(
                `.post-id-${id} .post__like`
              );
              console.log("3");
              if (type) {
                element.innerHTML = `<i class="fa-solid fa-heart"></i><div>총 좋아요 : ${like}</div>`;
              } else {
                element.innerHTML = `<i class="fa-regular fa-heart"></i><div>총 좋아요 : ${like}</div>`;
              }
            }
          }
        };
      };

      //레디스테이트가 변할때마다 이벤트리스너처럼 자동작동
    </script>
  </body>
</html>

piro20_Ajax_Pirostagram/server/templates/posts/main.html
{% load static %}{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.css"
    />
    <link rel="stylesheet" href="{% static 'posts/css/style.css' %}" />
  </head>
  <body>
    <div class="header">
      <a class="menu-btn title" href="{% url 'posts:main' %}">Pirostargram</a>

      {% if user.is_authenticated %}

      <span>{{user.username}} 님이 로그인중</span>
      <a class="menu-btn" href="{% url 'posts:create' %}">게시글 작성하기</a>
      <a href="{% url 'users:logout' %}">로그아웃</a>

      {% else %}
      <a class="social_login3" href="{% provider_login_url 'google' %}"
        >구글 로그인</a
      >
      <a class="social_login3" href="{% provider_login_url 'kakao' %}"
        >카카오 로그인</a
      >
      <a class="social_login3" href="{% provider_login_url 'naver' %}"
        >네이버 로그인</a
      >
      {% endif %}
    </div>

    <div class="posts_list">
      {% for post in posts %}
      <div class="post">
        {% if post.photo.url != '' %}
        <img src="{{post.photo.url}}" alt="제품 이미지" class="img" /><br />
        {% else %}
        <img
          src="{% static 'posts/image/no_img.png' %}"
          alt="대체 텍스트"
          class="img"
        /><br />
        {% endif %}
        <a class="post_title" href="{% url 'posts:detail' post.pk %}"
          >제목 : {{post.title}}</a
        >
        <div class="post_user">작성자 : {{post.user.username}}</div>
        <div class="post-id-{{ post.id }}">
          <div
            class="btn btn-primary post__like"
            onclick="onClickLike({{ post.id }},{{post.like}},'{{user.username}}')"
          >
            {% if post.is_like %}
            <i class="fa-solid fa-heart"></i>
            <div>총 좋아요 : {{post.like}}</div>
            {% else %}
            <i class="fa-regular fa-heart"></i>
            <div>총 좋아요 : {{post.like}}</div>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <script>
      const requestLike = new XMLHttpRequest();

      const onClickLike = (id, like, username) => {
        const url = "/like_ajax/";
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestLike.send(
          JSON.stringify({ id: id, like: like, username: username })
        );
        console.log("1");
      };

      //레디스테이트가 변할때마다 이벤트리스너처럼 자동작동
      requestLike.onreadystatechange = () => {
        if (requestLike.readyState === XMLHttpRequest.DONE) {
          console.log("2");
          if (requestLike.status < 400) {
            const { id, type, like } = JSON.parse(requestLike.response);
            const element = document.querySelector(
              `.post-id-${id} .post__like`
            );
            console.log("3");
            if (type) {
              element.innerHTML = `<i class="fa-solid fa-heart"></i><div>총 좋아요 : ${like}</div>`;
            } else {
              element.innerHTML = `<i class="fa-regular fa-heart"></i><div>총 좋아요 : ${like}</div>`;
            }
          }
        }
      };
    </script>
  </body>
</html>