SWIDEA_SITE/server/apps/devtools/urls.py
from django.urls import path
from .views import *

app_name = 'devtools'
urlpatterns = [
    path('',dev_list,name='list'),
    path('create/',create,name='create'),
    path('detail/<int:pk>/',detail,name='detail'),
    path('delete/<int:pk>/',delete,name='delete'),
    path('update/<int:pk>/',update,name='update'),
]

SWIDEA_SITE/server/apps/ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'
urlpatterns = [
    path('',idea_list,name='list'),
    path('create/',create,name='create'),
    path('detail/<int:pk>/',detail,name='detail'),
    path('delete/<int:pk>/',delete,name='delete'),
    path('update/<int:pk>/',update,name='update'),
    path('star_list/<int:pk>',star_list,name='star_list'),
    path('star_detail/<int:pk>',star_detail,name='star_detail'),
    path('interest/',interest,name='interest'),
]

SWIDEA_SITE/server/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.ideas.urls')),
    path('devtools/',include('apps.devtools.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/server/apps/devtools/models.py
from django.db import models

# Create your models here.
class Devtool(models.Model):
  name = models.CharField('이름',max_length=24)
  kind = models.CharField('종류', max_length=24)
  content = models.TextField('개발툴 설명')
  
  def __str__(self):
    return self.name

SWIDEA_SITE/server/apps/ideas/models.py
from django.db import models
from apps.devtools.models import *
# Create your models here.
class Idea(models.Model):
  title = models.CharField('제목',max_length=24)
  image = models.ImageField('이미지', blank=True, upload_to='ideas/%Y%m%d')
  content = models.TextField('아이디어 설명')
  interest = models.IntegerField('아이디어 관심도',default=0)
  updated_date = models.DateTimeField('수정일', auto_created=True,auto_now=True)
  #수정필요
  devtool = models.ForeignKey(Devtool,on_delete=models.CASCADE,verbose_name = '개발툴')
  
  #찜하기
  star = models.BooleanField(default = False)
  
  def __str__(self):
    return self.title

SWIDEA_SITE/server/apps/devtools/forms.py
from django import forms
from .models import Devtool

class DevForm(forms.ModelForm):
  class Meta():
    model = Devtool
    fields = ('__all__')

SWIDEA_SITE/server/apps/ideas/forms.py
from django import forms
from .models import Idea

class IdeaForm(forms.ModelForm):
  class Meta():
    model = Idea
    fields = ('title','image','content','interest','devtool')

SWIDEA_SITE/server/apps/devtools/views.py
from django.shortcuts import render, redirect
from .models import Devtool
from .forms import DevForm
# Create your views here.

def dev_list(request):
  devtools = Devtool.objects.all()
  search_txt = request.GET.get('search_txt')
  #필터링
  if search_txt:
    devtools = devtools.filter(name__contains=search_txt)

  ctx = {
    'devtools':devtools
  }
  return render(request,'devtools/devtool_list.html',ctx)

def create(request):
  if request.method == 'GET':
    form = DevForm()
    ctx = {'form' : form}
    return render(request,'devtools/devtool_create.html',ctx)
  
  form = DevForm(request.POST,  request.FILES)
  if form.is_valid():
    form = form.save()
  return redirect('devtools:detail',form.id)

def detail(request,pk):
  devtool = Devtool.objects.get(id=pk)

  related_ideas = devtool.idea_set.all()
  ctx = {'devtool':devtool, 'related_ideas':related_ideas}
  return render(request,'devtools/devtool_detail.html',ctx)

def update(request,pk):
  devtool = Devtool.objects.get(id=pk)
  if request.method == 'GET':
    #폼이 남아있는 상태로 보이도록함
    form = DevForm(instance=devtool)
    ctx = {
      'form' : form,
      'pk':pk
    } 
    return render(request,'devtools/devtool_update.html',ctx)
  
  #업데이트
  form = DevForm(request.POST,instance=devtool)
  if form.is_valid():
    form.save()
  return redirect('devtools:detail',pk)

def delete(request,pk):
  if request.method == 'POST':
    Devtool.objects.get(id=pk).delete()
  return redirect('devtools:list')

SWIDEA_SITE/server/apps/ideas/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import *
from .forms import IdeaForm
from django.core.paginator import Paginator

# Create your views here.
sort_temp='temp'
def idea_list(request):
  ideas = Idea.objects.all()
  sort = request.GET.get('sort')
  print(request.GET.get('sort'))
  if (request.GET.get('sort')) is None:
    global sort_temp
    if sort_temp == 'temp':
      sort = 'temp'
    else:
      sort = sort_temp
  else:
    sort = request.GET.get('sort')
  
  if sort == 'title':
    ideas = ideas.order_by('title')
  elif sort == 'pk':
    ideas= ideas.order_by('pk')
  elif sort == 'updated_date':
    ideas = ideas.order_by('-pk')
  elif sort == 'interest':
    ideas = ideas.order_by('-interest')
  elif sort == 'star':
    ideas = ideas.order_by('-star')
  paginator = Paginator(ideas, 4) # 한 페이지에 4개의 게시글을 보여줌
  page = request.GET.get('page')
  ideas = paginator.get_page(page)
  sort_temp = sort
  ctx = {
    'ideas':ideas,
    'paginator': paginator,
    
  }
  return render(request,'ideas/idea_list.html',ctx)

def create(request):
  if request.method == 'GET':
    form = IdeaForm()
    ctx = {'form' : form}
    return render(request,'ideas/idea_create.html',ctx)
  
  form = IdeaForm(request.POST,  request.FILES)
  if form.is_valid():
    form = form.save()
  return redirect('ideas:detail',form.id)

def detail(request,pk):
  idea = Idea.objects.get(id=pk)
  
  ctx = {'idea':idea}
  return render(request,'ideas/idea_detail.html',ctx)

def update(request,pk):
  idea = Idea.objects.get(id=pk)
  if request.method == 'GET':
    #폼이 남아있는 상태로 보이도록함
    form = IdeaForm(instance=idea)
    ctx = {
      'form' : form,
      'pk':pk
    } 
    return render(request,'ideas/idea_update.html',ctx)
  
  #업데이트
  form = IdeaForm(request.POST,request.FILES,instance=idea)
  if form.is_valid():
    form.save()
  return redirect('ideas:detail',pk)

def interest(request):
  pk = request.POST.get('pk', None) # ajax 통신을 통해서 template에서 POST방식으로 전달
  check = request.POST.get('check', None)
  idea = get_object_or_404(Idea, id=pk)
  if check == 'increase':
    idea_interest = idea.interest + 1
    idea.interest += 1
  else:
    idea_interest = idea.interest - 1
    idea.interest -= 1
  idea.save()
  context = {'interest' : idea_interest }
  return HttpResponse(json.dumps(context), content_type="application/json")
  # context를 json 타입으로



def delete(request,pk):
  if request.method == 'POST':
    Idea.objects.get(id=pk).delete()
  return redirect('ideas:list')


def star_list(request,pk):
  star_toggle = Idea.objects.get(id=pk)
  if star_toggle.star:
    star_toggle.star = False
  else:
    star_toggle.star = True
  star_toggle.save()
  return redirect('ideas:list')

def star_detail(request,pk):
  star_toggle = Idea.objects.get(id=pk)
  if star_toggle.star:
    star_toggle.star = False
  else:
    star_toggle.star = True
  star_toggle.save()
  return redirect('ideas:detail',pk)

SWIDEA_SITE/server/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'ideas/css/style.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.css"
    />
  </head>
  <body>
    <header class="navbar">
      <a href="/" class="logo"><h1>My SW Idea Manage</h1></a>
      <a href="{% url 'ideas:create' %}" class="logo"><h1>아이디어 등록</h1></a>
      <a href="{% url 'ideas:list' %}" class="logo"><h1>아이디어 관리</h1></a>
      <a href="{% url 'devtools:create' %}" class="logo"
        ><h1>개발툴 등록</h1></a
      >
      <a href="{% url 'devtools:list' %}" class="logo"><h1>개발툴 관리</h1></a>
    </header>
    {%block content%} {%endblock%}
  </body>
</html>
<link rel="stylesheet" href="{% static 'ideas/css/style.css' %}" />
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
  $(".click").click(function () {
    let pk = $(this).attr("value");
    let check = $(this).attr("name");
    $.ajax({
      // .click 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.
      type: "POST", // 데이터를 전송하는 방법을 지정
      url: "{% url 'ideas:interest' %}", // 통신할 url을 지정
      data: { pk: pk, check: check, csrfmiddlewaretoken: "{{ csrf_token }}" }, // 서버로 데이터 전송시 옵션
      dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단
      // 서버측에서 전송한 Response 데이터 형식 (json)

      success: function (response) {
        // 통신 성공시 - 동적으로 좋아요 갯수 변경, 유저 목록 변경
        $("#count-" + pk).html(response.interest);
      },
      error: function (request, status, error) {
        // 통신 실패시 - 로그인 페이지 리다이렉트

        window.location.replace("/create/");
        //  alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      },
    });
  });

  document.getElementById("mySelect").value =
    sessionStorage.getItem("selectedOption");

  document.getElementById("mySelect").addEventListener("change", function () {
    sessionStorage.setItem("selectedOption", this.value);
  });
</script>

SWIDEA_SITE/server/templates/devtools/devtool_create.html
{% extends 'base.html' %} {%block content%}
<div class="idea-list">
  <div class="head">
    <h1>DevTool Register</h1>
    <div>
      개발툴 등록 페이지입니다. 자신이 사용가능한 개발툴을 등록해 보세요.
    </div>
  </div>

  <form
    action="{% url 'devtools:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">submit</button>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/server/templates/devtools/devtool_detail.html
{% extends 'base.html' %} {% load static %} {%block content%}
<div class="idea-list">
  <div class="head">
    <h1>DevTool Detail</h1>
    <div>
      개발툴 세부내용 페이지입니다. 자신이 사용가능한 개발툴의 목록을 확인해
      보세요.
    </div>
  </div>

  <div class="content-wrapper">
    <div class="dev-info">
      <h2>{{devtool.name}}</h2>
      <p>{{devtool.kind}}</p>
      <p>{{devtool.content}}</p>
    </div>
    <div class="sw">> 만들 수 있는 sw 목록</div>
    {% for rel_idea in related_ideas %}
    <a href="{% url 'ideas:detail' rel_idea.pk %}" class="btn btn-success">
      {{rel_idea.title}}
    </a>
    <br />
    {% endfor %}
  </div>
  <form action="{% url 'devtools:delete' devtool.pk %}" method="POST">
    {%csrf_token%}
    <button type="submit" class="btn btn-danger">삭제</button>
  </form>
  <a href="{% url 'devtools:list' %}" class="btn btn-primary">목록</a>
  <a href="{% url 'devtools:update' devtool.pk %}" class="btn btn-primary"
    >수정</a
  >
</div>

{%endblock%}

SWIDEA_SITE/server/templates/devtools/devtool_list.html
{% extends 'base.html' %} {% load static %} {%block content%}

<div class="idea-list">
  <div class="head">
    <h1>DevTool List</h1>
    <div>
      개발툴 목록 페이지입니다. 자신이 사용가능한 개발툴의 목록을 확인해 보세요.
    </div>
  </div>
  <form action="#">
    <input
      class="form-control mx-2"
      type="input"
      name="search_txt"
      placeholder="이름.."
    />
  </form>
  <!-- 개발툴 리스트 반복문 -->
  <div class="content-wrapper2">
    {% for devtool in devtools %}
    <div class="item">
      <div class="dev-info-list">
        <a href="{% url 'devtools:detail' devtool.pk %}" class="devtool">
          {{devtool.name}}
        </a>
        <p class="devtool">{{devtool.kind}}</p>
        <p class="devtool">{{devtool.content}}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{%endblock%}

SWIDEA_SITE/server/templates/devtools/devtool_update.html
{% extends 'base.html' %} {%block content%}
<div class="idea-list">
  <div class="head">
    <h1>DevTool Detail Update</h1>
    <div>
      개발툴 세부내용 수정 페이지 입니다. 개발툴에 대해 수정사항이 있으면
      고쳐보아요.
    </div>
  </div>
  <form
    action="{% url 'devtools:update' pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/server/templates/ideas/idea_create.html
{% extends 'base.html' %} {%block content%}
<div class="idea-list">
  <div class="head">
    <h1>Idea Register</h1>
    <div>
      아이디어 등록 페이지 입니다. 당신의 아이디어를 잊지 말고 기록하세요!
    </div>
  </div>
  <form
    action="{% url 'ideas:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">submit</button>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/server/templates/ideas/idea_detail.html
{% extends 'base.html' %} {% load static %} {%block content%}
<div class="idea-list">
  <div class="head">
    <h1>Idea Detail</h1>
    <div>
      아이디어 세부내용 페이지입니다. 당신이 구현하려 한 아이디어들을 자세히
      살펴보세요.
    </div>
  </div>

  <div class="content-wrapper">
    <!-- <img class="item"> -->
    {% if idea.image.url != null and idea.image.url != '' %} {% if idea.star%}
    <div class="image-container">
      <img src="{{ idea.image.url }}" alt="" />
      <a class="star-icon" href="{% url 'ideas:star_list' idea.pk %}">
        <i class="fa-regular fa-star outline"></i>
        <i class="fa-solid fa-star fill check"></i>
      </a>
    </div>
    {% else %}
    <div class="image-container">
      <img src="{{ idea.image.url }}" alt="" />
      <a class="star-icon" href="{% url 'ideas:star_list' idea.pk %}">
        <i class="fa-regular fa-star outline"></i>
        <i class="fa-solid fa-star fill"></i>
      </a>
    </div>
    {% endif %} {% else %} {% if idea.star %}
    <div class="image-container">
      <img src="{% static 'ideas/image/no_img.png' %}" alt="대체텍스트" />
      <a class="star-icon" href="{% url 'ideas:star_list' idea.pk %}">
        <i class="fa-regular fa-star outline"></i>
        <i class="fa-solid fa-star fill check"></i>
      </a>
    </div>
    {% else %}
    <div class="image-container">
      <img src="{% static 'ideas/image/no_img.png' %}" alt="대체텍스트" />
      <a class="star-icon" href="{% url 'ideas:star_list' idea.pk %}">
        <i class="fa-regular fa-star outline"></i>
        <i class="fa-solid fa-star fill"></i>
      </a>
    </div>
    {% endif %} {% endif %}
    <div class="info">
      <a href="{% url 'ideas:detail' idea.pk %}" class="title">
        {{idea.title}}
      </a>
      <p class="devtool">예상 개발툴: {{idea.devtool}}</p>
      <p class="interest">
        아이디어 관심도:
        <button value="{{idea.pk}}" class="click" name="increase">+</button>
        <span id="count-{{idea.pk}}">{{idea.interest}}</span>
        <button value="{{idea.pk}}" class="click" name="decrease">-</button>
      </p>
    </div>
  </div>
  <form action="{% url 'ideas:delete' idea.pk %}" method="POST">
    {%csrf_token%}
    <button type="submit" class="btn btn-danger">삭제</button>
  </form>
  <a href="{% url 'ideas:list' %}" class="btn btn-primary">목록</a>
  <a href="{% url 'ideas:update' idea.pk %}" class="btn btn-primary">수정</a>
</div>

{%endblock%}

SWIDEA_SITE/server/templates/ideas/idea_list.html
{% extends 'base.html' %} {% load static %} {%block content%}
<div class="idea-list">
  <div class="head">
    <h1>Idea List</h1>
    <div>나의 아이디어를 잊지 말고 기록해보세요</div>
  </div>

  <!-- 정렬기준 -->
  <div class="sort">
    <form>
      <select name="sort" onchange="form.submit()" id="mySelect">
        <option>---------</option>
        <option value="star">찜하기순</option>
        <option value="title">이름순</option>
        <option value="pk">등록순</option>
        <option value="updated_date">최신순</option>
        <option value="interest">인기순</option>
      </select>
    </form>
  </div>

  <div class="list_main">
    <!-- 아이디어 리스트 반복문 -->

    {% for idea in ideas %}
    <div class="content-wrapper">
      <!-- <img class="item"> -->
      {% if idea.image.url != null and idea.image.url != '' %} {% if idea.star%}
      <div class="image-container">
        <img src="{{ idea.image.url }}" alt="" />
        <a class="star-icon" href="{% url 'ideas:star_list' idea.pk %}">
          <i class="fa-regular fa-star outline"></i>
          <i class="fa-solid fa-star fill check"></i>
        </a>
      </div>
      {% else %}
      <div class="image-container">
        <img src="{{ idea.image.url }}" alt="" />
        <a class="star-icon" href="{% url 'ideas:star_list' idea.pk %}">
          <i class="fa-regular fa-star outline"></i>
          <i class="fa-solid fa-star fill"></i>
        </a>
      </div>
      {% endif %} {% else %} {% if idea.star %}
      <div class="image-container">
        <img src="{% static 'ideas/image/no_img.png' %}" alt="대체텍스트" />
        <a class="star-icon" href="{% url 'ideas:star_list' idea.pk %}">
          <i class="fa-regular fa-star outline"></i>
          <i class="fa-solid fa-star fill check"></i>
        </a>
      </div>
      {% else %}
      <div class="image-container">
        <img src="{% static 'ideas/image/no_img.png' %}" alt="대체텍스트" />
        <a class="star-icon" href="{% url 'ideas:star_list' idea.pk %}">
          <i class="fa-regular fa-star outline"></i>
          <i class="fa-solid fa-star fill"></i>
        </a>
      </div>
      {% endif %} {% endif %}
      <div class="info">
        <a href="{% url 'ideas:detail' idea.pk %}" class="title">
          {{idea.title}}
        </a>
        <p class="devtool">예상 개발툴: {{idea.devtool}}</p>
        <p class="interest">
          아이디어 관심도:
          <button value="{{idea.pk}}" class="click" name="increase">+</button>
          <span id="count-{{idea.pk}}">{{idea.interest}}</span>
          <button value="{{idea.pk}}" class="click" name="decrease">-</button>
        </p>
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- 페이지네이션 -->
  <div class="pagination">
    {% if ideas.has_previous %}
    <a href="?page=1">처음</a>
    <a href="?page={{ ideas.previous_page_number }}">이전</a>
    {% endif %}
    <span>{{ ideas.number }}</span>
    <span>/</span>
    <span>{{ ideas.paginator.num_pages }}</span>
    {% if ideas.has_next %}
    <a href="?page={{ ideas.next_page_number }}">다음</a>
    <a href="?page={{ ideas.paginator.num_pages }}">마지막</a>
    {% endif %}
  </div>
</div>
{%endblock%}

SWIDEA_SITE/server/templates/ideas/idea_update.html
{% extends 'base.html' %} {%block content%}
<div class="idea-list">
  <div class="head">
    <h1>Idea Detail Update</h1>
    <div>
      아이디어 세부내용 수정 페이지 입니다. 아이디어를 구체화하거나 내용을
      변경해 보아요.
    </div>
  </div>
  <form
    action="{% url 'ideas:update' pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
</div>
{%endblock%}